config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'dashboard#show'
  get '/land_acknowledgments', to: 'land#show'
  get '/gardens/:id/plants/:plant_id/edit', to: 'plants#edit'
  patch '/gardens/:id/plants/:plant_id/edit', to: 'plants#update'
  post '/gardens', to: 'gardens#create'
  get '/gardens/new', to: 'gardens#new'
  get '/gardens/:id', to: 'gardens#show'
  get '/gardens/:id/plants', to: 'plants#search'
  post '/gardens/:id/plants', to: 'plants#create'

  get '/moon_booty', to: 'application#contributors'

  delete '/gardens/:id/plants/:plant_id', to: 'plants#destroy'

  delete '/gardens/:id', to: 'gardens#destroy'

  # post '/gardens/:id/plants/new', to: 'plants#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_lunar_rec
  helper_method :get_weather, :ip_address

  def authorize_user
    unless session[:user_id]
      flash[:alert] = 'Oopsy daisy! Please log in below to view that page.'
      redirect_to '/'
    end
  end

  def set_lunar_rec
    @moon_data = MoonFacade.get_moon_data(Time.new.to_i)
    @recommendation = MoonHelper.rec(@moon_data.phase)
  end

  def ip_address
    if Rails.env.production?
      request.remote_ip
    else
      Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
    end
  end

  def get_weather
    location = IpFacade.get_ip_location(ip_address)
    lat = location.coordinates.split(",").first
    long = location.coordinates.split(",").last
    WeatherFacade.get_weather(lat, long)
  end

  def contributors
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize_user

  def show
    @gardens = GardenFacade.get_gardens(session[:user_id])[0..5]
  end



end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :authorize_user
  
  def new; end

  def create
    garden_info = params.permit(:name, :notes, :cardinal_direction)
    if params[:notes].strip == "" || params[:name].strip == "" 
      flash[:alert] = 'Please fill in all fields'
      redirect_to '/gardens/new'
    else
      garden_info[:user_id] = session[:user_id].to_i
      GardenFacade.create_garden(garden_info)
      flash[:alert] = 'Garden Created'
      redirect_to dashboard_path
    end
  end

  def show
    @garden = GardenFacade.get_garden_data(session[:user_id], params[:id])
    @plants = PlantTrackingFacade.get_plants(session[:user_id], params[:id])[0..10]
  end

  def destroy
    GardenFacade.destroy_garden(session[:user_id], params[:id])
    redirect_to dashboard_path
    flash[:alert] = 'Garden Deleted'
  end
end

app/controllers/land_controller.rb
class LandController < ApplicationController
  def show
    if !params[:location]
      @ll = IpFacade.get_ip_location(ip_address)
    else
      @ll = GeocoderFacade.get_coordinates(params[:location])
    end
    @lands = LandFacade.get_land_data(@ll.coordinates) 
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authorize_user
  def search
    @garden_id = params[:id]
    @results = PlantFacade.search_plant_data(params[:search])
  end

  def create
    data = {
      "user_id": session[:user_id],
      "garden_id": params[:id],
      "name": params[:plant_name],
      "plant_id": params[:plant_api_id],
      "moon_phase": @moon_data.phase,
      "date_planted": Date.today
    }

    PlantTrackingFacade.create_plant(data)
    redirect_to "/gardens/#{params[:id]}"
  end

  def destroy
    PlantTrackingFacade.destroy_plant(session[:user_id], params[:id], params[:plant_id])
    redirect_to "/gardens/#{params[:id]}"
  end

  def edit
    @garden_id = params[:id]
    @plant_id = params[:plant_id]
    @plant = params.permit(:date_planted,
                            :moon_phase,
                            :bounty_amount,
                            :pruning_behaviors,
                            :notes)
  end

  def update
    data = {
      "date_planted": params[:date_planted],
      "moon_phase": params[:moon_phase],
      "bounty_amount": params[:bounty_amount],
      "pruning_behaviors": params[:pruning_behaviors],
      "notes": params[:notes]

    }
    PlantTrackingFacade.edit_plant(session[:user_id], params[:id], params[:plant_id], data)
    redirect_to "/gardens/#{params[:id]}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    auth_hash = request.env['omniauth.auth']
    if auth_hash['credentials']['token'].present?
      user = UserFacade.find_or_create_user(auth_hash[:info])
      set_session(user)
      redirect_to '/dashboard'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def set_session(user)
    session[:user_id] = user.id
    session[:email] = user.email
    session[:image] = user.image
    session[:first_name] = user.name.split.first
    session[:last_name] = user.name.split.last
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/contributors.html.erb
<div class="background-container">
<a href="/">
<img class="moon-booty-image" src="https://media0.giphy.com/media/XPydpT9cmZaUxF23iX/200w.gif?cid=82a1493bl048mxe59bpulzhggtlpt47wjwklhgxl94gxgcs5&rid=200w.gif&ct=g" alt="moon winking and showing their butt">
</a>
<div class="stars"></div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<div class="moon-booty container-fluid">
  <p class="display-5 text-center">Contributors:</p>
  <br>
  <div class="container-fluid text-center display-6">
    <div class="moon-booty-row">
      <a href="https://www.linkedin.com/in/andrewkingdev/" style="color:white">
        <div class="col-md-4">Andrew King ♊️</div>
      </a>
      <a href="https://www.linkedin.com/in/bryce-wein/" style="color:white">
        <div class="col-md-4 ms-auto">Bryce Wein ♍️</div>
      </a>
    </div>
    <div class="row">
      <a href="https://www.linkedin.com/in/casey-fazio-7ba04149/" style="color:white">
      <div class="col-md-15 ms-md-auto">Casey Fazio ♊️</div>
      </a>
      <a href="https://www.linkedin.com/in/jenniferlhalloran/" style="color:white">
      <div class="col-md-5 ms-md-auto">Jenn Halloran ♉️</div>
      </a>
    </div>
    <div class="row">
      <a href="https://www.linkedin.com/in/jim-riddle-b6718037/" style="color:white">
        <div class="col-md-5 me-auto">Jim Riddle ♊️</div>
      </a>
      <a href="https://www.linkedin.com/in/stephen-wilkens/" style="color:white">
      <div class="col-md-15 ms-auto">Stephen Wilkins ♌️</div>
      </a>
    </div>
  </div>
  </div>
<div class="twinkling"></div>
  

app/views/dashboard/show.html.erb
<div class="container text-center d-flex" style="max-height: 100%; margin-left: 40px;">

  <div class="side-bar-left col-sm-3 mw-100">
    <div class="logo">
      <a href="/moon_booty">
        <%= render inline: Rails.root.join('public/moon-garden-logo.svg').read %>
      </a>
    </div>
  </div>


  <div class="dash-main-bar col-sm-10" style="max-height: 100%">
    <%= render partial: "shared/header" %>
    <div class="dash-container">
      <div class="dash-profile-pic">
        <img src="<%=session[:image]%>" alt="user image"/>
      </div>
      <h1>
        <%=session[:first_name]%>'s Gardens
      </h1>
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= button_to "Add New Garden", "/gardens/new", method: :get, class: "btn btn-bd-primary btn-lg", local: true %>
      </div>
      <br>

      <div class="row row-cols-1 row-cols-md-2 ">
        <% @gardens.each_with_index do |garden, index|%>
          <div class="col">
            <div class="card mb-3">
              <div class="card-img-top-fluid">
                <%= image_tag "garden_images/#{index + 1}.jpg", alt: 'icon', class: "img-fluid rounded-start"%>
                <div class="card-body">
                  <h5 class="card-title"><%= link_to "#{garden.name}", "/gardens/#{garden.id}" %></h5>
                  <p class="card-text">Notes:
                    <%= garden.notes %></p>
                  <p class="card-text">Cardinal Direction:
                    <%= garden.cardinal_direction %></p>
                  <div id="<%= garden.id %>">

                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#deleteModal<%= garden.id %>">
                      Remove Garden
                    </button>
                  </div>

                  <div class="modal fade" id="deleteModal<%= garden.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          Deleting
                          <%= garden.name %>
                          will also delete all the plants you are tracking in this garden!
                        </div>
                        <div class="modal-footer">
                          <%= button_to "Remove Garden", "/gardens/#{garden.id}", method: :delete, class:"btn btn-danger"%>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>

  <%= render partial: "shared/widgets" %>

</div>

app/views/gardens/new.html.erb
<div class="container text-center d-flex" style="max-height: 100%, max-width: 100%; margin-left: 40px;">
  <div class="side-bar-left col-sm-3 mw-100">
    <div class="logo">
      <a href="/moon_booty">
        <%= render inline: Rails.root.join('public/moon-garden-logo.svg').read %>
      </a>
    </div>
  </div>

  <div class="dash-main-bar col-sm-10" style="max-height: 100%">

    <%= render partial: "shared/header" %>

    <div class="dash-container">
      <h1>
        Enter Garden Details
      </h1>

      <div class="form-floating">
      <%= form_with url: gardens_path, local:true do |form| %>
      <div class="form-floating">
        <%= form.text_field :name, { class: "form-control" } %>
        <%= form.label "Garden Name" %>
      </div>

      <div class="form-floating">
        <%= form.text_area :notes, { class: "form-control" } %>
        <%= form.label "Notes" %>
      </div>

      <div class="form-floating">
        <%= form.select :cardinal_direction, ['North','South','East', 'West'], {}, class: "form-select", id: "floatingSelect" %>
        <%= form.label "Cardinal Direction", { for: "floatingSelect" } %>
      </div>

      <div class="d-grid gap-2 col-6 mx-auto">
        <%= form.submit class: "btn btn-outline-secondary" %>
      </div>
    <% end %>
    </div>

  </div>
</div>


<%= render partial: "shared/widgets" %>

</div>

app/views/gardens/show.html.erb
<div class="container text-center d-flex" style="max-height: 100%; margin-left: 40px;">

  <div class="side-bar-left col-sm-3 mw-100">
    <div class="logo">
      <a href="/moon_booty">
        <%= render inline: Rails.root.join('public/moon-garden-logo.svg').read %>
      </a>
    </div>

  </div>

  <div class="dash-main-bar col-sm-10" style="max-height: 100%">
    <%= render partial: "shared/header" %>
    <div class="dash-container">
      <h1 class="display-5"><%= @garden.name %>'s Plant Tracker</h1>

      <h3>Planted
        <%= @garden.cardinal_direction %>
        Facing</h3>
      <p class="lead">
        <%= @garden.notes %></p>
      <br>
      <div class="d-flex justify-content-center" role="search">
        <%= form_with url: "/gardens/#{@garden.id}/plants", method: :get, local: true do |f| %>
        <%= f.hidden_field :query, value: "name" %>

        <div class="form-floating" id="formSelect">
          <%= f.text_field :search, class: "form-control me-2", type: "search" %>
          <%= f.label "Plant Name Search", for: "formSelect" %>
        </div>

        <%= f.submit "Find Plants to add to Garden", class: "btn btn-success" %>

      <% end %>
    </div>
    <br>
    <% @plants.each_with_index do |plant, index| %>

      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapseOne">
              <%= plant.name %>
            </button>
          </h2>
          <div id="collapse<%= index %>" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="plant-<%= plant.id %>">
              <div class="accordion-body">

                <dl class="row">
                  <% if plant.date_planted != "" %>
                    <dt class="col-sm-4">Date Planted:</dt>
                    <dd class="col-sm-9"><%= plant.date_planted.to_datetime.strftime('%m-%d-%Y') %></dd>
                  <% end %>
                  <dt class="col-sm-4">Moon Phase During Planting:</dt>
                  <dd class="col-sm-9"><%= plant.moon_phase %></dd>

                  <dt class="col-sm-4">Amount Produced:</dt>
                  <dd class="col-sm-9"><%= plant.bounty_amount %></dd>

                  <dt class="col-sm-4">Pruning Behaviors:</dt>
                  <dd class="col-sm-9"><%= plant.pruning_behaviors %></dd>

                  <dt class="col-sm-4">Plant Notes:</dt>
                  <dd class="col-sm-9"><%= plant.notes %></dd>
                </dl>

                <%= form_with url: "/gardens/#{@garden.id}/plants/#{plant.id}/edit", method: :get, local: true do |f| %>
                <%= f.hidden_field :date_planted, value: plant.date_planted %>
                <%= f.hidden_field :moon_phase, value: plant.moon_phase %>
                <%= f.hidden_field :bounty_amount, value: plant.bounty_amount %>
                <%= f.hidden_field :pruning_behaviors, value: plant.pruning_behaviors %>
                <%= f.hidden_field :notes, value: plant.notes %>
                <div class="d-grid gap-2 justify-content-md-end">
                  <%= f.submit "Add Tracking Info", class: "btn btn-light" %>
                <% end %>

                <div id="<%= plant.id %>">

                  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal<%= plant.id %>">
                    Remove Plant
                  </button>
                </div>

                <div class="modal fade" id="deleteModal<%= plant.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure you want to delete
                        <%= plant.name %>
                        ??
                      </div>
                      <div class="modal-footer">
                        <%= button_to "Remove Plant", "/gardens/#{@garden.id}/plants/#{plant.id}", method: :delete, class:"btn btn-danger"%>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

<%= render partial: "shared/widgets" %>

</div>

app/views/land/show.html.erb
<div class="container d-flex" style="max-height: 100%; margin-left: 40px;">

  <div class="side-bar-left col-sm-3">
    <div class="logo">
      <a href="/moon_booty">
        <%= render inline: Rails.root.join('public/moon-garden-logo.svg').read %>
      </a>
    </div>

    <button class="btn btn-warning" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">More Information & Map Directions</button>
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <h5 class="offcanvas-title text-center" id="offcanvasWithBothOptionsLabel">Why Acknowledge?</h5>
      <div class="offcanvas-body">
        <p>"The land itself is sacred, and it is not easy to draw lines that divide it up into chunks that delineate who “owns” different parts of land. In reality, we know that the land is not something to be exploited and “owned”, but something to be honoured and treasured." We have included this map for the same reason the map was made and is shared - "to bring an awareness of the real lived history of Indigenous peoples and nations in a long era of colonialism." <cite title="Source Title">native-land.ca</cite></p>
        <a href="https://native-land.ca/about/why-it-matters/" class="btn btn-success d-flex justify-content-center">Go to source</a>
        <br>
        <h5 class="offcanvas-title text-center" id="offcanvasWithBothOptionsLabel">Map Directions</h5>
        <div class="offcanvas-body">
          <p><strong>Search for your location and click the links to learn more about the area you occupy.</strong></p>
          <p>"Native Land is an app to help map Indigenous territories, treaties, and languages."</p>
        </div>
        <h5 class="offcanvas-title text-center" id="offcanvasWithBothOptionsLabel">Links To More Information</h5>
        <div class="offcanvas-body">
          <p><a href="https://www.farmersalmanac.com/why-garden-by-the-moon-20824">Why We Garden By The Moon</a></p>
          <p><a href="https://www.denverlibrary.org/blog/books/heidie/whats-growin-history-and-politics-seed-saving">The History and Politics of Seed Saving</a></p>
          <p><a href="https://www.denverlibrary.org/blog/books/heidie/seed-rematriation">Land Back, Seeds Back</a></p>
          <p><a href="https://www.teenvogue.com/story/ruth-wilson-gilmore-qa">Geography and Liberation</a></p>
        </div>
      </div>
    </div>

    <br>
    <br>
    <div class="card d-flex" style="width: 17.5rem;">
      <div class="card-body">
        <h5 class="card-title">Why?</h5>
        <h6 class="card-subtitle mb-2 text-muted">Because It's Important</h6>
        <p class="card-text">We chose to include land acknowledgments because when working with the soil it's important to think about the history of the land we are working with and how we have learned to work with the land in these ways in the first place.</p>
      </div>
    </div>
  </div>

  <div class="dash-main-bar col-sm-10 text-center" style="max-height: 100%">
    <%= render partial: "shared/header" %>

    <div class="dash-container">

      <figure>
        <blockquote class="blockquote">
          <p>“When we talk about land, land is part of who we are. It’s a mixture of our blood, our past, our current, and our future. We carry our ancestors in us, and they’re around us. As you all do.”</p>
        </blockquote>
        <figcaption class="blockquote-footer">
          Mary Lyons (Leech Lake Band of Ojibwe) <cite title="Source Title">NativeGov.org</cite>
        </figcaption>
      </figure>

      <div class="d-flex">
        <iframe allowtransparency="yes" scrolling="no" style="border: 0px solid #FFFFFF; width:1020px; height:500px; overflow: hidden;" src="https://native-land.ca/wp-content/themes/Native-Land-Theme/embed/embed.html?maps=languages&position=<%= "#{@ll.coordinates}" %>"></iframe>
      </div>

      <p class="lead">These are territories in the area. Click the links to learn more.</p>
      <% @lands.each do |land| %>
        <%= link_to land.name, land.description %>
      <% end %>

      <form class="d-flex justify-content-center" role="search">
        <%= form_with url: '/land_acknowledgments', method: :get, local: true do |form| %>
          <div class="form-floating">
            <%= form.text_field :location, { class: "form-control me-2" } %>
            <%= form.label "Enter Your Location" %>
            <br>
            <%= form.submit "Search", class: "btn btn-light" %>

          <% end %>
        </div>
      </form>
    </div>
  </div>

  <%= render partial: "shared/widgets" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moon Garden</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag ('https://cdn-icons-png.flaticon.com/512/180/180700.png') %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div id="message" class="alert alert-primary">
        <%= msg %>
      </div>
    <% end %>

      <%= yield %>

  </body>
</html>

app/views/plants/edit.html.erb
<div class="container text-center d-flex" style="max-height: 100%; margin-left: 40px;">

  <div class="side-bar-left col-sm-3 mw-100">
    <div class="logo">
      <a href="/moon_booty">
        <%= render inline: Rails.root.join('public/moon-garden-logo.svg').read %>
      </a>
    </div>
  </div>

  <div class="dash-main-bar col-sm-10" style="max-height: 100%">
    <%= render partial: "shared/header" %>
    <div class="dash-container">
      <div id="form">
        <%= form_with url: "/gardens/#{@garden_id}/plants/#{@plant_id}/edit", method: :patch, local: true do |f| %>
          <div class="mb-3">
            <% if @plant[:date_planted] == "" %>
              <%= f.label :date_planted, "Date Planted" %>
              <%= f.date_field :date_planted, value: Date.today.strftime('%Y-%m-%d'), class: "form-control" %>
            <% else %>
              <%= f.label :date_planted, "Date Planted" %>
              <%= f.date_field :date_planted, value: @plant[:date_planted].to_datetime.strftime('%Y-%m-%d') , class: "form-control" %>
            <% end %>
          </div>
          <div class="mb-3">
            <%= f.label :moon_phase, "Moon Phase During Planting" %>
            <%= f.text_field :moon_phase, value: @plant[:moon_phase], class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :bounty_amount, "Amount Produced" %>
            <%= f.number_field :bounty_amount, value: @plant[:bounty_amount], class: "form-control"  %>
          </div>
          <div class="mb-3">
            <%= f.label :pruning_behaviors, "Pruning Behaviors" %>
            <%= f.text_field :pruning_behaviors, value: @plant[:pruning_behaviors], class: "form-control"   %>
          </div>
          <div class="mb-3">
            <%= f.label :notes, "Plant Notes" %>
            <%= f.text_area :notes, value: @plant[:notes], class: "form-control"   %>
          </div>
          <div class="mb-3">
            <%= f.submit "Update Plant", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render partial: "shared/widgets" %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg header-container">
  <div class="container">
    <% if !session[:user_id] %>
      <!-- <a class="navbar-brand" href="#">Navbar</a> -->
      <a class="oauth-container btn darken-4 white black-text" href='/auth/google_oauth2' style="text-transform:none">
        <div class="left">
          <img width="20px" style="margin-top:7px; margin-right:8px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
        </div>
        Login with Google
      </a>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if session[:user_id] %>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <a class="nav-link" href=<%= dashboard_path %>>My Gardens</a>
        <a class="nav-link" href=<%= root_path %>>About</a>
        <a class="nav-link" href=<%= land_acknowledgments_path %>>Land Acknowledgments</a>
        <a class="nav-link" href=<%= logout_path %>>Logout</a>
      </div>
    </div>
  <% end %>
</div>
</nav>

app/views/shared/_widgets.html.erb
<div class="side-bar-right col-sm-3 flex text-center">

  <div class="card" style="width: 18rem;">
    <br>
    <div class="container">
      <img src="https://moonphase.guide/module/MVitCdDJoN21yWGNDaU5uL2ZKQjVMRkI1UVptSFMxMGZyQW9FQzRKV2d3NUhGWlpZV3RmSzRMMW56bVBFNWt0clJKM21uTTRiTVFBZWpHM0RLVklYcWc9PQ.png"/>
    </div>
    <div class="card-body">
      <dt class="card-text">Lunar Recommendation: <%= @recommendation %></dt>
    <dd class="card-text">Illumination:
      <%= @moon_data.illumination %>%</dd>
    <dd class="card-text">Moon Type:
      <%= @moon_data.name %></dd>
    </div>
  </div>
  <br>
  <br>
  <% weather = get_weather %>
  <div class="card" style="width: 18rem;">
    <div class="container">
      <img class="weather-image rounded" src="http://openweathermap.org/img/wn/<%= weather.icon %>@2x.png">
      <div class="card-body">
        <h5 class="card-title">Today's Weather</h5>
        <p class="card-text">Today's temperature is a 
        <% if weather.temp < 69 %>
          balmy
        <% elsif weather.temp >= 69 && weather.temp < 90 %>
          warm 
        <% else %>
          blistering
        <% end%>
        <strong><%= weather.temp %>°</strong> with a touch of <strong><%= weather.description %>.</strong></p>
      </div>
    </div>
  </div>
</div>